service: swole

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-west-1

package:
  exclude:
    - "**/*.ts"
    - "test/**"
    - "scripts/**"
    - ".vscode/**"
    - "*"

functions:
  http:
    handler: dist/handler.http
    timeout: 3
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline